version: '3'
services:
  php_apache:
    container_name: php_stack_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - local_network
    depends_on:
      - mysql
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_UPLOAD_MAX_FILESIZE: 2048M
      APACHE_POST_MAX_SIZE: 2048M
      APACHE_MAX_EXECUTION_TIME: 600
      APACHE_MAX_INPUT_TIME: 600
      APACHE_MEMORY_LIMIT: 2048M
    command: >
      bash -c "a2enmod rewrite &&
      echo 'Timeout 600' >> /etc/apache2/apache2.conf &&
      apache2-foreground"

  mysql:
    image: mysql:8.1.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bhali
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql  
    networks:
      - local_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.1
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - local_network
  
  postgres:
    image: postgres:16.1
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bhali
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgres
    networks:
      - local_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - local_network        
    depends_on:
      - mysql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8083:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - local_network
    depends_on:
      - postgres

networks:
  local_network: